### ISSUE TITLE
Add option to exclude / remove some UDAs

### ISSUE THREAD

**Issue by pawamoy** [ralphbean/bugwarrior#623]
I would like an option to remove the `githubnamespace` and `githubbody` UDAs from the pulled tasks.

- the namespace is causing me unicity issues (see #601)
- the body is sometimes very large and I don't need it in taskwarrior (I already have the links to the issue, which is enough)

In general, it could be done for all services at once as it's not specific to a particular service. Maybe an option like `SERVICE.exclude_udas` and/or its opposite `SERVICE.include_udas`.

**Comment by ryneeverett** [comment]
I'm not opposed to this if there's sufficient use case. (See discussion in #601.)

**Comment by ralphbean** [comment]
@pawamoy - Are you still having new issues with the `namespace` after #654?

**Comment by wookietreiber** [comment]
I guess @pawamoy is out: https://github.com/ralphbean/bugwarrior/pull/626#issuecomment-515024677

**Comment by pawamoy** [comment]
Hi, sorry, I missed this mention :slightly_smiling_face:

I deleted all my taskwarrior tasks and am reimported them through bugwarrior, and have no duplicates. I cannot confirm *for sure* that the issue is solved, but it seems to be :slightly_smiling_face: 

EDIT: actually my config was pulling from only one namespace, let me check with multiple ones.

**Comment by pawamoy** [comment]
So it seems to be working well on an initial pull with multiple namespaces: I got no duplicates. However, I got a lot of duplicates in the following scenario:

- initial pull with one namespace
- added other namespaces
- second pull

I had duplicated, identical issues in Taskwarrior after that. All fields were equal, including the GitHub namespace UDA. I'm not sure what happened.

**Comment by pawamoy** [comment]
Not interested anymore, feel free to reopen if needed!

**Comment by khaeru** [comment]
I am still interested in this feature.

**Comment by ryneeverett** [comment]
If we were to implement this, I think the way to go would be to add a hook in `db.synchronize` at the beginning of each loop through the `issue_generator` that deletes the given keys.

However, I'm still not convinced there's a sufficient use case. Hopefully we've fixed the unicity bugs. If it's large uda's you don't use, you can set `annotation_comments = False` and `description_length = 0`. What am I missing?

**Comment by khaeru** [comment]
> If it's large uda's you don't use, you can set `annotation_comments = False` and `description_length = 0`. What am I missing?

Only that the last comment here was in April 2020, and it seems (per blame [here](https://github.com/ralphbean/bugwarrior/blame/2643a4b041b2a34723e54d3d5c88e72f43367a23/bugwarrior/docs/services/github.rst#L154)) those features you mention were added in November 2020 or later. So it's just that no one came back to notify that this issue had been addressed 🙂 (AFAICT also CHANGELOG.rst is no longer updated and there's no change log in the docs, so maybe that's why the addition was not very noticeable.)

Thanks for now doing so. I'll check if these meet the need and comment again.

**Comment by khaeru** [comment]
[This hint](https://github.com/ralphbean/bugwarrior/blame/develop/bugwarrior/docs/services/github.rst#L165) (from #837, i.e. September 2021) to use **`static_fields`** did the trick. Since the function of that option aligns pretty closely with the request of the OP here, I think the issue can probably be closed again, @ryneeverett.

It seems the option was added in #407 (2016) but not 'til last September did anyone (@djmitche per https://github.com/ralphbean/bugwarrior/issues/835#issuecomment-913238162 —thanks!) make explicit that it could be used in this way.
